# Generated by Django 3.0.8 on 2020-07-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200723_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.IntegerField(choices=[(1, 'Doing'), (2, 'Done')]),
        ),
    ]
